baseURL = "https://lifelabnepal.com/"
languageCode = "en-us"
title = "LifeLAB Nepal"
disableKinds = ["taxonomy", "term", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
